version: '3.1'
services:
  postgres:
    image: postgres:alpine
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=example
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql