version: '3.1'

services:
  postgres:
      image: postgres
      hostname: postgres
      environment:
        - POSTGRES_PASSWORD=example
      volumes:
        - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
      ports:
        - "5432:5432"